services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
 
  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-config:
    image: bitnami/kafka:3.5
    depends_on:
      - kafka
    volumes:
      - ./config/topic-wait-config.sh:/init-topics.sh
    entrypoint: ["/bin/bash", "/init-topics.sh"]
 
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-latest
      container_name: sqlserver
      ports:
        - "1433:1433"
      environment:
        SA_PASSWORD: "SAPassword!"
        ACCEPT_EULA: "Y"
      volumes:
        - ./sql/startup/startup.sh:/start.sh # This enables the SQL Server Agent which is required for CDC transactions
      entrypoint: ["/bin/bash", "/start.sh"]
      user: root
 
  connect:
    image: debezium/connect:2.7.3.Final
    container_name: connect
    depends_on:
      - kafka
    ports:
      - "8083:8083"  # Kafka Connect REST API
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=connect-cluster
      - CONFIG_STORAGE_TOPIC=connect-configs
      - OFFSET_STORAGE_TOPIC=connect-offsets
      - STATUS_STORAGE_TOPIC=connect-status
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - REST_ADVERTISED_HOST_NAME=connect
      - PLUGIN_PATH=/kafka/connect
 
      # Increase Jetty server request size limits
      - KAFKA_HEAP_OPTS=-Xms512M -Xmx1G
      - CONNECT_JETTY_HEADER_BUFFER_SIZE=65536
      - CONNECT_JETTY_REQUEST_HEADER_SIZE=65536
      - CONNECT_JETTY_RESPONSE_HEADER_SIZE=65536

  consumer-customer:
    container_name: consumer-customer
    build:
      context: ./consumers
      dockerfile: customer/Dockerfile
    depends_on:
      - kafka
      - sqlserver
      - connect
    env_file:
      - ./consumers/customer/.env

  consumer-order:
    container_name: consumer-order
    build:
      context: ./consumers
      dockerfile: order/Dockerfile
    depends_on:
      - kafka
      - sqlserver
      - connect
    env_file:
      - ./consumers/order/.env